### PR TITLE
fix(react): allows radio's icon to be appear checked (icon)

### LINKED ISSUE #208: RadioGroup is broken
Screen Shot 2021-03-19 at 7 58 26 PM

Unable to select radio

### PR DESCRIPTION
**Pull request by schne324**
resolves #208

### CODE REVIEW

File: packages/react/src/components/Icon/index.tsx [hunk 1]
```diff
@@ -18,6 +18,7 @@ const Icon = forwardRef<HTMLDivElement, IconProps>(
     const [IconSVG, setIcon] = useState<React.ComponentType<any> | null>(null);
 
     useEffect(() => {
+      isMounted.current = true;
```
Comment (scurker) [inline packages/react/src/components/Icon/index.tsx:21]: huh, interesting 👀

**Review by scurker — APPROVED** [review]
